# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/guilds.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/guilds.proto\x12\x0bhuddle_chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n\x05Guild\x12\x10\n\x08guild_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04icon\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08is_owner\x18\x06 \x01(\x08\x12\x12\n\nhas_unread\x18\x07 \x01(\x08\"(\n\x15GuildsByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"<\n\x16GuildsByUserIdResponse\x12\"\n\x06guilds\x18\x01 \x03(\x0b\x32\x12.huddle_chat.Guild\"V\n\x12\x43reateGuildRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04icon\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"8\n\x13\x43reateGuildResponse\x12!\n\x05guild\x18\x01 \x01(\x0b\x32\x12.huddle_chat.Guild\"7\n\x12\x44\x65leteGuildRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08guild_id\x18\x02 \x01(\x03\"8\n\x13\x44\x65leteGuildResponse\x12!\n\x05guild\x18\x01 \x01(\x0b\x32\x12.huddle_chat.Guild2\x96\x02\n\x0cGuildService\x12^\n\x11GetGuildsByUserId\x12\".huddle_chat.GuildsByUserIdRequest\x1a#.huddle_chat.GuildsByUserIdResponse\"\x00\x12R\n\x0b\x43reateGuild\x12\x1f.huddle_chat.CreateGuildRequest\x1a .huddle_chat.CreateGuildResponse\"\x00\x12R\n\x0b\x44\x65leteGuild\x12\x1f.huddle_chat.DeleteGuildRequest\x1a .huddle_chat.DeleteGuildResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.guilds_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GUILD._serialized_start=69
  _GUILD._serialized_end=229
  _GUILDSBYUSERIDREQUEST._serialized_start=231
  _GUILDSBYUSERIDREQUEST._serialized_end=271
  _GUILDSBYUSERIDRESPONSE._serialized_start=273
  _GUILDSBYUSERIDRESPONSE._serialized_end=333
  _CREATEGUILDREQUEST._serialized_start=335
  _CREATEGUILDREQUEST._serialized_end=421
  _CREATEGUILDRESPONSE._serialized_start=423
  _CREATEGUILDRESPONSE._serialized_end=479
  _DELETEGUILDREQUEST._serialized_start=481
  _DELETEGUILDREQUEST._serialized_end=536
  _DELETEGUILDRESPONSE._serialized_start=538
  _DELETEGUILDRESPONSE._serialized_end=594
  _GUILDSERVICE._serialized_start=597
  _GUILDSERVICE._serialized_end=875
# @@protoc_insertion_point(module_scope)
